### ISSUE TITLE
Patch doesn't work on current Steam Release

### ISSUE THREAD

**Issue by drojf** [wf1264/meakashi-ru#1]
The current Steam release has Unity version 5.5.3p3, but your Meakashi patch has unity version 5.5.3p1 (for Mangagamer/GOG).

If you wish to support installing your mod to the Steam release, you should generate another `sharedassets0.assets` file for the steam release. Then use the same naming scheme from here: https://github.com/orian34/meakashi/releases/tag/v1.6.0
- Steam version (5.5.3p3) should be called `sharedassets0.assets`
- Mangagamer/GOG version (5.5.3p1) should be called `Windows-GOG-MG-5.5.3p1.languagespecificassets`
    - This is the same file you already have. You just have to rename it. 

**I may be able to generate these UI files for you, if you send me the assets you used.**

----

Otherwise, **if you only want to support modding the Mangagamer/GOG release**, tell me so I can update the installer with this information.

**Comment by wf1264** [comment]
I will be very grateful for your help if it possible to generate these UI files.
I sended the assets on email.

**Comment by drojf** [comment]
Hi, see download link below. You should replace the existing sharedassets with the one in this archive.

https://1drv.ms/u/s!Ar-lAVeetlqhhMF2ysBlnVPsiMlH_g?e=mJl9vb

Please note the following:

1. For some reason, Meakashi 5.5.3p1 and 5.5.3p3's title screen buttons are in a different order. To make a long story short, people using the 5.5.3.p1 version (GOG) will see the Russian title screen buttons, but people using the 5.5.3p3 (Steam, MG) will see the English title screen buttons. All other buttons/images don't have this problem. You don't need to do anything, I think most people will be OK with the title screen buttons not being translated.
2. I've created [a repo used for building the Russian version of the sharedassets](https://github.com/drojf/ui-editing-scripts-ru), and I'll add you as a contributor. If at a later date you feel like updating the rest of the sharedassets, you just have to fill in the images in the `assets/images` folder, then I can build it.
3. I'm assuming you didn't add a custom font as I didn't see any fonts in the files you sent me. The sharedassets I generated just use the same fonts our normal mod comes with.

**Comment by wf1264** [comment]
Done. I replaced the existing sharedassets and added file Windows-GOG-5.5.3p1.languagespecificassets.
Also I have updated them first with UnityTextModifier.py and my changes.json file (maybe this can be automated in the future?).

**Comment by drojf** [comment]
>  I replaced the existing sharedassets and added file Windows-GOG-5.5.3p1.languagespecificassets.

You should add the Unix ones too, so that Linux/Mac players can play the game.

> Also I have updated them first with UnityTextModifier.py and my changes.json file (maybe this can be automated in the future?).

I need to revise what those are for... (I haven't had to use them before). Could you upload your `changes.json` file here?

**Comment by drojf** [comment]
> You should add the Unix ones too, so that Linux/Mac players can play the game.

Don't do this yet, as you said I should see how that part is meant to be automated

**Comment by drojf** [comment]
I think you just replace the `assets/text-edits.json` file in the ui-editing repo - if you send your `changes.json` to me I can update the repo and generate the sharedassets again.

**Comment by wf1264** [comment]
changes.json
[changes.zip](https://github.com/wf1264/meakashi-ru/files/10335218/changes.zip)

**Comment by drojf** [comment]
Here's the updated sharedassets, with the `changes.json` already applied. Please include all the files in the release.

https://1drv.ms/u/s!Ar-lAVeetlqhhMF345TphT8ivzHkaQ?e=Iz3QNf

I've also committed the `changes.json` renamed as `assets/text-edits.json` in the git repository.

----

I haven't yet added documentation on how to generate the translator files (`.languagespecificassets`), but in short you run

`py build.py meakashi --translation`

This includes all the images and also runs the `UnityTextModifier.py` automatically (it always ran it, but I forgot that you need to update the `assets/text-edits.json`

Then the files will be placed in the `output/translation` folder.

**Comment by wf1264** [comment]
Done. Thank you for your help.

**Comment by drojf** [comment]
I noticed you renamed the release to `Meakashi.Patch.RU.7z`, which is fine, but please let me know if you rename the file next time, as the installer currently relies on a link like this:

https://github.com/wf1264/meakashi-ru/releases/latest/download/Meakashi.Patch.RU.7z

So if you change the filename, you also need to change the download link in the installer.

Just to be clear, I've already fixed it on my end, just letting you know for next time.
