### ISSUE TITLE
Translation doesn't work with 07th-mod installer due to missing `HigurashiEp05` folder

### ISSUE THREAD

**Issue by drojf** [wf1264/meakashi-ru#2]
We had a report that the Russian patch doesn't work if you install it via the 07th-mod installer, due to the wrong folder structure. 

The 07th-mod installer requires a `HigurashiEp05` folder at the root of the language translation archive to work correctly.

You just need to move all the files inside a `HigurashiEp05` folder at the root of the archive to fix it.

I also checked ep6-8 and they don't have this problem.

Aplogies if I missed this [last time we updated the archive](https://github.com/wf1264/meakashi-ru/issues/1), I should have noticed it.

----

### Current V1.02 Archive (Missing HigurashiEp05 folder at root)

![image](https://user-images.githubusercontent.com/1249449/218284159-136e7733-5fe8-4262-a72b-10b323a7a5c8.png)

### Old V1.01 Archive (Has the HigurashiEp05 Folder)

![image](https://user-images.githubusercontent.com/1249449/218284172-3da49bcf-7e4d-49d9-a74f-a8965b268fc5.png)

**Comment by wf1264** [comment]
Done.

**Comment by drojf** [comment]
Just did a test RU install and it seems to work fine now, thanks
